video: rockchip: mpp: fix 64-bit division compile issue
err note:
undefined reference to `__aeabi_uldivmod''

Signed-off-by: Yandong Lin <yandong.lin@rock-chips.com>
Change-Id: I2572d1a89edfbf3a6fb347318b7e031ff2bc48d1
(cherry picked from commit e60ac2564ff6836bb34373caca8fa7bd907a4aeb)