input: touchscreen: gsl3673_800x1280: Fix build as module
drivers/input/touchscreen/gsl3673_800x1280.c:68:11: fatal error: 'gsl3680b_zm97f.h' file not found

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I4754dafc101df625c557a777829e32b42f9d768c
(cherry picked from commit 571548a6569ee806f4e6438c2392e035f6b95c50)