video: rockchip: rga3: Fix compilation error on kernel-4.19
drivers/video/rockchip/rga3/rga_iommu.c:38:11: error: implicit declaration of function 'kmap' [-Werror=implicit-function-declaration]
   vaddr = kmap(pages[taipage_num - 1]);

Signed-off-by: Yu Qiaowei <cerf.yu@rock-chips.com>
Change-Id: I3f570c4812f4c308001cdd894799682faa18203e
(cherry picked from commit a322f85b9162fad0914e57bb630b3ca6e53c1247)