input: touchscreen: gt1x: set vfs-only exports into their own namespace
According to gki commit d483eed85ffb ("ANDROID: GKI: set vfs-only exports into their own namespace").

ERROR: modpost: module gt1x-ts uses symbol filp_open from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I2b25adf85977f90958292ef2af91c1ab6e5aa3e4
(cherry picked from commit 42a2baccb2382bafcf78ba3c06dad0bbe31aa328)