soc: rockchip: io-domain: fix module compile error
Fix compile error when build to module:
ERROR: modpost: "of_find_regulator_by_node" [drivers/soc/rockchip/io-domain.ko] undefined!

Fixes: bc2ba01c8835 ("soc: rockchip: io-domain: dump power supply-map when probe")

Signed-off-by: Jianqun Xu <jay.xu@rock-chips.com>
Change-Id: I38490ed4129b500c3b3828c4f689a93c7ba93a67
(cherry picked from commit 713d5a769d3185c3cd75068fd31fa55eb6753926)