soc: rockchip: pm_config: Fix build failure for !MODULE
ERROR: modpost: "of_find_regulator_by_node" [drivers/soc/rockchip/rockchip_pm_config.ko] undefined!
ERROR: modpost: "mem_sleep_current" [drivers/soc/rockchip/rockchip_pm_config.ko] undefined!
ERROR: modpost: "freeze_secondary_cpus" [drivers/soc/rockchip/rockchip_pm_config.ko] undefined!

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: Ib02b095cad3811b1b3026b2a7851fbcbc0abfc65
(cherry picked from commit 1bf0a32481374104a258666c25c5272a024a6017)