PCI: rockchip: Fix compile error without CONFIG_PCIEASPM
drivers/pci/controller/dwc/pcie-dw-rockchip.c: In function 'rk_pcie_downstream_dev_to_d0':
drivers/pci/controller/dwc/pcie-dw-rockchip.c:2207:38: error: 'struct pci_dev' has no member naned 'l1ss'

Signed-off-by: Shawn Lin <shawn.lin@rock-chips.com>
Change-Id: I67c0ed74183bc5bf7cb8975b8bcbcc4bebaa5ad5
(cherry picked from commit 15d9d94d2e21180cc7a35e5d3a7d2e2b28bc5095)