video: rockchip: mpp: fix gcc-6 compile error without AV1DEC driver
drivers/video/rockchip/mpp/mpp_service.o: In function `mpp_add_driver':
drivers/video/rockchip/mpp/mpp_service.c:102: undefined reference to `av1dec_driver_register'

Signed-off-by: Jianqun Xu <jay.xu@rock-chips.com>
Change-Id: Ibf2effb98ce7c0c2219d3bbd762dd8c34530626f
(cherry picked from commit 649f030b09b854d2bd3867766372062d462a0fd8)