arm64/configs: enable CONFIG_SQUASHFS_LZO for rockchip_linux_defconfig
Download snap "gnome-3-38-2004" (113) from channel "stable" will report
the below error:

Filesystem uses "lzo" compression. This is not supported
error: cannot perform the following tasks:
- Mount snap "gnome-3-38-2004" (113) (systemctl command
[start snap-gnome\x2d3\x2d38\x2d2004-113.mount] failed with exit status.

Signed-off-by: Caesar Wang <wxt@rock-chips.com>
Change-Id: Id35c140a482d41cb411fb62ba200d92804e814e5
(cherry picked from commit 9b20a518367b086d28c962b454e7306f0f1ab020)