net: wireless: rockchip_wlan: bcmdhd: Fix out-of-srctree build
../drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/aiutils.c:25:10: fatal error: 'typedefs.h' file not found

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I425cb52776bb1b3294b8ef67c951b04afe2288a9
(cherry picked from commit 95a8c1b877460fc5bd8483ac26aa4d7db451fc6c)