arm64: rockchip_gki.config: Temporarily disable CONFIG_ROCKCHIP_MULTI_RGA
ERROR: modpost: "arch_dma_prep_coherent" [drivers/video/rockchip/rga3/rga3.ko] undefined!
ERROR: modpost: "iommu_get_dma_domain" [drivers/video/rockchip/rga3/rga3.ko] undefined!

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I7c095ea3ee96da6547309235abb6936db0e9e8c6
(cherry picked from commit 0c782f48ae6944acedab48232b592ddf3738b78e)