PCI: aspm_ext: Fix Add missing MODULE_LICENSE()
ERROR: modpost: missing MODULE_LICENSE() in drivers/pci/pcie/aspm_ext.o

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: Id365aba7a73f02cc2c61882b46937250e64af01c
(cherry picked from commit cf03561e5ec9f2f8b41a992f3b8ca19b9c3b9e47)