PCI: rockchip: dw: Fix error in calling dw_pcie_prog_inbound_atu function
drivers/pci/controller/dwc/pcie-dw-ep-rockchip.c:533:70: error: too few arguments to function call, expected 6, have 5
        ret = dw_pcie_prog_inbound_atu(pci, free_win, bar, cpu_addr, as_type);

Change-Id: Iaa3083f6cfe4edbba422fff5a245515f40c70db4
Signed-off-by: Jon Lin <jon.lin@rock-chips.com>
(cherry picked from commit 62d3af47b81dcaa03eb3d5348c87b74e4b490f42)