net: phy: rk630phy: Fix the compile error
drivers/net/phy/rk630phy.c:97:37: error: incompatible pointer types passing 'int *' to parameter of type 'size_t *' (aka 'unsigned long *') [-Werror,-Wincompatible-pointer-types]
                efuse_buf = nvmem_cell_read(cell, &len);
                                                  ^~~~
./include/linux/nvmem-consumer.h:62:56: note: passing argument to parameter 'len' here
void *nvmem_cell_read(struct nvmem_cell *cell, size_t *len);

Signed-off-by: David Wu <david.wu@rock-chips.com>
Change-Id: Iee69c589b532b067b57290bcb3e39f3402ea83e7
(cherry picked from commit 77f8a69780746598bd01bdd9227bb666429fc0b8)