net: wireless: rockchip: rkwifi: bcmdhd: Fix for rt_mutex
drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/dhd_linux.c:20403:3: error: member reference base type 'void' is not a structure or union
                mutex_destroy(mtx);
                ^~~~~~~~~~~~~~~~~~
./include/linux/mutex_rt.h:53:48: note: expanded from macro 'mutex_destroy'

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I087fb3469769b6e0c23f5e937514be3452f2197a
(cherry picked from commit e321a068b472578f4888208ae70f902d7a3cc5a2)