arm64: rockchip_gki.config: Temporarily disable CONFIG_PCIE_DW_ROCKCHIP
ERROR: modpost: "dw_pcie_write_dbi2" [drivers/pci/controller/dwc/pcie-dw-rockchip.ko] undefined!

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I450aa9a91753de5cca6c2f1a99f14988e324e1c8
(cherry picked from commit 112dd880358140a2b7299c9bf399101b67b08433)